### ISSUE TITLE
Switch from print to click.echo()

### ISSUE THREAD

**Issue by alkafir** [pynog/python-ares#12]
Flask uses this nice library called **click**, which, among other things, provides a Python 2/3 compatible `echo()` function which works in pretty much the same way as `print` does.

Example:
```python
    from click import echo
    
    echo("This is an example")

    with open('file', 'w') as f:
        echo("This goes to file", file=f)

    # The following will work in both Python 2/3
    # but won't render nicely in Python 2
    print('This will', 'print a tuple', 'in python 2') # But a space-separated string in Python 3
```

The rationale behind this proposal is that using the standard `print` function/statement in Python 2/3 compatible code is prone to errors and leads to different behaviours depending on the running version - in our case we have some print statements which are Python 3 incompatible but - and this provides a simple, standardised way to avoid them.

**Comment by pynog** [comment]
Good idea !!!
